### ISSUE TITLE
Performance evaluation

### ISSUE THREAD

**Issue by hohMiyazawa** [umgefahren/image-comp-lib-rust#1]
In the hope it is useful, here is my experience testing out your project.

# Getting the program running

Your repository has no build instructions, but it nevertheless seems to work straight out of the box with ``cargo build --release``. The build.sh script appears to have "apple-darwin" hardcoded. Otherwise no issues compiling the code.

# Compression

Using ``./image-compressor comp infile.png outfile.bin`` on my standard mixed-content test corpus, I obtained the following result:
- Compression matches zstd very closely.
- image-comp beats PNG for about 25% of the images, and gets beaten at around 75% of the images in my corpus.
- In no cases were the image-comp files more than twice the size of PNG.
- Memory and CPU usage were not unreasonably high.
- The compression/decompression roundtrip was lossless for all images tested.

![img2](https://user-images.githubusercontent.com/58218853/105121871-68570780-5ad5-11eb-990b-9f20928653df.png)

Regarding the included test images img 1_4, they appear to not be particularly dense PNGs. With a modern PNG encoder, they can be (losslessly) reduced in size by about 15-20%. As an example, the PNG format is capable of compressing img_2 from the lead of the readme down to 9.9MB. That should be a more fair baseline if beating PNG is your ultimate goal.

Good luck!

**Comment by umgefahren** [comment]
First of all thanks for the detailed response! You are helping me a lot!
About getting the project running: Indeed the build script is actually just a script to build a universal Mac OS binary, because cargo doesn't support that out of the box. I will rename it to reflect that. There's actually no need to compile the code yourself, I provided binaries for every major operating system in the latest release, but there's no difference to compiling it yourself. I'll add an explanation for that.
I would be very interested in your corpus, because my images were only images from my photo library, because those were the only ones, I was completely sure that I'm allowed to use them.
I want to apologize for making false claims regarding the performance and I want to thank you for making this graph. Could you give me permission to use it or even better tell me how you made it?
Yes the compression is completely lossless. That could have been pointed out more, I'm very sorry if that's unclear.
Regarding CPU and memory usage: Which operating system are using? I've experienced some differences in that manner across the operating systems. I am personally quite unhappy about the time it takes to compress a file.
The images I uploaded were created out of my Apple Photo Library. I somehow assumed, that Apple would use the best and most modern encoder. I guess I was wrong about that. I'll recompress the images and upload the new files.
Maybe beating PNG is too ambitious and it's a bit frustrating to see PNG achieving lower file sizes with a less complex algorithm.

**Comment by hohMiyazawa** [comment]
>I provided binaries for every major operating system in the latest release

That's something I did not expect. Re-reading the readme, the mention of "provided binaries" is actually pretty clear.

>my images were only images from my photo library, because those were the only ones, I was completely sure that I'm allowed to use them

A very sensible consideration, and highly relevant when distributing them. I recommend using some collection of [standard test images](https://en.wikipedia.org/wiki/Standard_test_image), which need not be included in the repository. Generally, it's hard to make a good estimate of performance without testing on many images.

>I want to apologize for making false claims regarding the performance

I see no false claims. You claimed to occasionally beat PNG, which you do.

>Could you give me permission to use it or even better tell me how you made it?

You have my permission to use it in any way you see fit, although it would not be of much use since it will quickly get outdated as your algorithm evolves. I can try to post a simple script that gives you the necessary data from any collection of images.

>Regarding CPU and memory usage

I did not look very closely at this. It did however use little enough memory that multiple instances could be run in parallel, and compression was quick enough that the entire test could be repeated in minutes, which is quite snappy for an experimental compressor.

>Yes the compression is completely lossless. That could have been pointed out more, I'm very sorry if that's unclear.

It was in no way unclear that you have made a lossless format. I have merely checked that it was indeed the case for anything I threw at it.

>I'll recompress the images and upload the new files

I see you have gotten around to this already. optipng should make a fair baseline indeed.

>Maybe beating PNG is too ambitious and it's a bit frustrating to see PNG achieving lower file sizes with a less complex algorithm.

It's certainly hard to do with a completely novel approach (the kind of approach compression needs). In general, PNG seems to be at a sweet spot where it gets a surprisingly much out of very simple tools.

**Comment by hohMiyazawa** [comment]
README seems to have more immediate information now as well

Benchmarking your own image library, in a directory with just pngs:
``for i in *.png; do ./image-compressor comp "$i" "$i".bin; done``
Or if you have GNU parallel:
``parallel ./image-compressor comp {} {}.bin ::: *.png``

A script for getting the relative size, like in my plot (probably works on mac too, but tell me if something needs to be tweaked):
```
#!/bin/bash
sum=0
for i in *.png; do
	size1=$(du -b "$i.bin" | cut -f1)
	size2=$(du -b "$i" | cut -f1)
	sum=$(dc <<< "$sum $size1+p")
	bc -l <<< "$size1/$size2" >> results.txt
done
sort -g results.txt
echo "$sum"
```
